// ABOUTME: Request ID middleware for correlation and distributed tracing
// ABOUTME: Generates unique request IDs and propagates them through request/response lifecycle
//
// Licensed under either of Apache License, Version 2.0 or MIT License at your option.
// Copyright ©2025 Async-IO.org

//! Request ID middleware for request correlation
//!
//! This middleware generates a unique UUID v4 for each incoming request,
//! adds it to the request extensions for use by handlers, and includes it
//! in the response headers for client-side correlation.

use axum::{extract::Request, middleware::Next, response::Response};
use http::HeaderValue;
use tracing::Span;
use uuid::Uuid;

/// Request ID header name
const REQUEST_ID_HEADER: &str = "x-request-id";

/// Request ID middleware that generates and propagates correlation IDs
///
/// This middleware:
/// 1. Generates a unique UUID v4 for each request
/// 2. Adds the request ID to request extensions for handler access
/// 3. Records the request ID in the current tracing span
/// 4. Includes the request ID in the response header
///
/// # Example
///
/// ```rust,ignore
/// use axum::Router;
/// use axum::middleware;
///
/// let app = Router::new()
///     .route("/", get(handler))
///     .layer(middleware::from_fn(request_id_middleware));
/// ```
pub async fn request_id_middleware(mut req: Request, next: Next) -> Response {
    // Generate unique request ID
    let request_id = Uuid::new_v4().to_string();

    // Record request ID in current tracing span
    let span = Span::current();
    span.record("request_id", &request_id);

    // Add to request extensions for handler access
    req.extensions_mut().insert(RequestId(request_id.clone()));

    // Process request
    let mut response = next.run(req).await;

    // Add request ID to response header
    if let Ok(header_value) = HeaderValue::from_str(&request_id) {
        response
            .headers_mut()
            .insert(REQUEST_ID_HEADER, header_value);
    }

    response
}

/// Request ID extractor for use in handlers
///
/// This can be extracted in any Axum handler to access the request ID
/// generated by the middleware.
///
/// # Example
///
/// ```rust,ignore
/// async fn handler(Extension(request_id): Extension<RequestId>) -> String {
///     format!("Request ID: {}", request_id.0)
/// }
/// ```
#[derive(Debug, Clone)]
pub struct RequestId(pub String);

impl RequestId {
    /// Get the request ID as a string slice
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for RequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::{
        body::Body,
        http::{Request as HttpRequest, StatusCode},
        middleware,
        routing::get,
        Extension, Router,
    };
    use tower::ServiceExt;

    async fn test_handler(Extension(request_id): Extension<RequestId>) -> String {
        format!("Request ID: {}", request_id.as_str())
    }

    #[tokio::test]
    async fn test_request_id_middleware_generates_id() -> Result<(), Box<dyn std::error::Error>> {
        let app = Router::new()
            .route("/", get(test_handler))
            .layer(middleware::from_fn(request_id_middleware));

        let request = HttpRequest::builder().uri("/").body(Body::empty())?;

        let response = app.oneshot(request).await?;

        // Check that response has request ID header
        let request_id_header = response.headers().get(REQUEST_ID_HEADER);
        assert!(request_id_header.is_some(), "Request ID header not present");

        // Verify it's a valid UUID format
        if let Some(header_value) = request_id_header {
            let request_id_str = header_value.to_str()?;
            assert!(
                Uuid::parse_str(request_id_str).is_ok(),
                "Request ID is not a valid UUID"
            );
        }

        Ok(())
    }

    #[tokio::test]
    async fn test_request_id_available_in_handler() -> Result<(), Box<dyn std::error::Error>> {
        let app = Router::new()
            .route("/", get(test_handler))
            .layer(middleware::from_fn(request_id_middleware));

        let request = HttpRequest::builder().uri("/").body(Body::empty())?;

        let response = app.oneshot(request).await?;

        assert_eq!(response.status(), StatusCode::OK);

        // The handler should successfully access the request ID
        let body = axum::body::to_bytes(response.into_body(), usize::MAX).await?;
        let body_str = String::from_utf8(body.to_vec())?;
        assert!(body_str.starts_with("Request ID: "));

        Ok(())
    }
}
