// ABOUTME: Main entry point for @pierre/shared-types package
// ABOUTME: Re-exports all shared types for convenient importing

// Social types (friend connections, insights, reactions)
export type {
  FriendStatus,
  ShareVisibility,
  InsightType,
  ReactionType,
  TrainingPhase,
  FriendConnection,
  FriendWithInfo,
  DiscoverableUser,
  NotificationPreferences,
  UserSocialSettings,
  SharedInsight,
  InsightReaction,
  AdaptedInsight,
  FeedAuthor,
  ReactionCounts,
  FeedItem,
  SocialMetadata,
  ListFriendsResponse,
  PendingRequestWithInfo,
  PendingRequestsResponse,
  FriendConnectionResponse,
  SearchUsersResponse,
  FeedResponse,
  ShareInsightResponse,
  ListInsightsResponse,
  ListAdaptedInsightsResponse,
  ReactionResponse,
  AdaptInsightResponse,
  SocialSettingsResponse,
  ShareInsightRequest,
  UpdateSocialSettingsRequest,
  ListInsightsParams,
  InsightSuggestion,
  ListSuggestionsResponse,
  ShareFromActivityRequest,
  GetSuggestionsParams,
} from './social.js';

// Coach types (AI coaching personas, store, versions)
export type {
  CoachCategory,
  CoachVisibility,
  PublishStatus,
  Coach,
  ForkCoachResponse,
  CreateCoachRequest,
  UpdateCoachRequest,
  CoachMetadata,
  ListCoachesResponse,
  CoachVersion,
  ListVersionsResponse,
  RevertVersionResponse,
  FieldChange,
  CoachDiffResponse,
  StoreCoach,
  StoreCoachDetail,
  StoreMetadata,
  BrowseCoachesResponse,
  SearchCoachesResponse,
  CategoryCount,
  CategoriesResponse,
  InstallCoachResponse,
  UninstallCoachResponse,
  InstallationsResponse,
  CoachAssignment,
  AssignCoachResponse,
  UnassignCoachResponse,
  ListAssignmentsResponse,
} from './coaches.js';

// Auth types (users, login, OAuth)
export type {
  UserRole,
  UserStatus,
  UserTier,
  User,
  AdminUser,
  LoginResponse,
  RegisterResponse,
  FirebaseLoginResponse,
  ProviderStatus,
  ExtendedProviderStatus,
  ProvidersStatusResponse,
  OAuthApp,
  OAuthAppCredentials,
  OAuthProvider,
  McpToken,
  UserManagementResponse,
  ApproveUserRequest,
  SuspendUserRequest,
} from './auth.js';

// API types (chat, prompts, common patterns)
export type {
  Conversation,
  Message,
  ActivityPillar,
  PromptCategory,
  PromptSuggestionsResponse,
  ApiMetadata,
  PaginatedResponse,
  ListResponse,
} from './api.js';

// Admin types (API keys, admin tokens, A2A protocol, dashboard)
export type {
  ApiKeyStatus,
  ApiKey,
  ApiKeysResponse,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
  AdminPermission,
  AdminToken,
  AdminTokensResponse,
  CreateAdminTokenRequest,
  CreateAdminTokenResponse,
  AdminTokenAudit,
  AdminTokenUsageStats,
  TierUsage,
  DashboardOverview,
  RateLimitOverview,
  RequestLog,
  RequestStats,
  RequestFilter,
  ToolUsageBreakdown,
  A2AClient,
  A2AClientRegistrationRequest,
  A2AClientCredentials,
  A2ASession,
  A2ARateLimitStatus,
  A2AUsageStats,
  A2AUsageRecord,
  A2ADashboardOverview,
  SetupStatusResponse,
  ProvisionedKey,
  MilestoneConfig,
  DistanceMilestoneConfig,
  StreakConfig,
  MilestoneRelevanceScores,
  DistanceRelevanceScores,
  StreakRelevanceScores,
  RelevanceConfig,
  ActivityFetchLimitsConfig,
  SocialInsightsConfig,
} from './admin.js';
