// Integration tests for stateless HMAC-signed CSRF token manager
// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 dravr.ai

#![allow(missing_docs)]

use pierre_auth::security::csrf::CsrfTokenManager;
use uuid::Uuid;

#[test]
fn test_generate_csrf_token() -> anyhow::Result<()> {
    let manager = CsrfTokenManager::default();
    let user_id = Uuid::new_v4();

    let token = manager.generate_token(user_id)?;

    // Token should be a non-empty base64url string
    assert!(!token.is_empty(), "CSRF token should not be empty");

    // Token should be a valid base64url string (alphanumeric + - _ chars)
    assert!(
        token
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'),
        "CSRF token should be valid base64url"
    );
    Ok(())
}

#[test]
fn test_validate_csrf_token() -> anyhow::Result<()> {
    let manager = CsrfTokenManager::default();
    let user_id = Uuid::new_v4();
    let other_user_id = Uuid::new_v4();

    let token = manager.generate_token(user_id)?;

    // Valid token for correct user
    assert!(
        manager.validate_token(&token, user_id).is_ok(),
        "Valid token should pass validation"
    );

    // Invalid token for different user
    assert!(
        manager.validate_token(&token, other_user_id).is_err(),
        "Token should fail for different user"
    );

    // Invalid token string
    assert!(
        manager.validate_token("invalid_token", user_id).is_err(),
        "Invalid token should fail validation"
    );
    Ok(())
}

#[test]
fn test_csrf_token_tamper_resistance() -> anyhow::Result<()> {
    let manager = CsrfTokenManager::default();
    let user_id = Uuid::new_v4();

    let token = manager.generate_token(user_id)?;

    // Tamper with the token by converting to bytes, flipping one, and rebuilding
    let mut token_bytes: Vec<u8> = token.into_bytes();
    if !token_bytes.is_empty() {
        token_bytes[0] ^= 0x01;
    }
    let tampered = String::from_utf8(token_bytes)?;

    assert!(
        manager.validate_token(&tampered, user_id).is_err(),
        "Tampered token should fail validation"
    );
    Ok(())
}

#[test]
fn test_csrf_different_secrets_reject() -> anyhow::Result<()> {
    let manager_a = CsrfTokenManager::with_secret(b"secret-a-32-bytes-padding-xxxxx");
    let manager_b = CsrfTokenManager::with_secret(b"secret-b-32-bytes-padding-xxxxx");
    let user_id = Uuid::new_v4();

    let token = manager_a.generate_token(user_id)?;

    // Token generated with secret A should not validate with secret B
    assert!(
        manager_b.validate_token(&token, user_id).is_err(),
        "Token should fail when validated with a different secret"
    );

    // But should validate with the original manager
    assert!(
        manager_a.validate_token(&token, user_id).is_ok(),
        "Token should pass with the original secret"
    );
    Ok(())
}

#[test]
fn test_csrf_from_jwt_secret_deterministic() -> anyhow::Result<()> {
    let jwt_secret = "test-jwt-secret-for-csrf-derivation";
    let manager_1 = CsrfTokenManager::from_jwt_secret(jwt_secret);
    let manager_2 = CsrfTokenManager::from_jwt_secret(jwt_secret);
    let user_id = Uuid::new_v4();

    let token = manager_1.generate_token(user_id)?;

    // Token generated by one instance should validate on another with same secret
    assert!(
        manager_2.validate_token(&token, user_id).is_ok(),
        "Token should validate across instances with same JWT secret"
    );
    Ok(())
}

#[test]
fn test_csrf_token_survives_restart_simulation() -> anyhow::Result<()> {
    let jwt_secret = "persistent-server-secret";
    let user_id = Uuid::new_v4();

    // Simulate first server instance generating a token
    let token = {
        let manager = CsrfTokenManager::from_jwt_secret(jwt_secret);
        manager.generate_token(user_id)?
    };

    // Simulate server restart — new manager from same secret
    let restarted_manager = CsrfTokenManager::from_jwt_secret(jwt_secret);
    assert!(
        restarted_manager.validate_token(&token, user_id).is_ok(),
        "Token should survive server restart when using persistent secret"
    );
    Ok(())
}
