// ABOUTME: Unit tests for TransactionGuard RAII wrapper
// ABOUTME: Validates auto-rollback behavior, commit semantics, and retry patterns
//
// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 dravr.ai
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
#![allow(missing_docs)]

use std::sync::atomic::{AtomicU32, Ordering};

use pierre_core::errors::AppError;
use pierre_database::backends::factory::Database;
use pierre_database::backends::shared::transactions::{retry_transaction, TransactionGuard};
use pierre_database::database::test_utils::create_test_db;
use sqlx::Row;

/// The guard is generic over the `SQLx` database, so every test runs its
/// body against whichever backend the factory opened: `pool` is bound to
/// that backend's pool and the body is compiled once per arm.
macro_rules! with_test_pool {
    (|$pool:ident| $body:block) => {
        match create_test_db()
            .await
            .expect("Failed to create test database")
        {
            Database::SQLite(db) => {
                let $pool = db.pool().clone();
                create_items_table(
                    &$pool,
                    "CREATE TABLE IF NOT EXISTS test_items (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        name TEXT NOT NULL,
                        value INTEGER NOT NULL
                    )",
                )
                .await;
                $body
            }
            #[cfg(feature = "postgresql")]
            Database::PostgreSQL(db) => {
                let $pool = db.pool().clone();
                create_items_table(
                    &$pool,
                    "CREATE TABLE IF NOT EXISTS test_items (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        name TEXT NOT NULL,
                        value INTEGER NOT NULL
                    )",
                )
                .await;
                $body
            }
        }
    };
}

/// Create the simple table the tests insert into, in the backend's dialect.
async fn create_items_table<DB: sqlx::Database>(pool: &sqlx::Pool<DB>, ddl: &str)
where
    for<'c> &'c sqlx::Pool<DB>: sqlx::Executor<'c, Database = DB>,
    for<'q> DB::Arguments<'q>: sqlx::IntoArguments<'q, DB>,
{
    sqlx::query(ddl)
        .execute(pool)
        .await
        .expect("Failed to create test table");
}

/// Count rows in the `test_items` table
async fn count_items<DB: sqlx::Database>(pool: &sqlx::Pool<DB>) -> i64
where
    for<'c> &'c sqlx::Pool<DB>: sqlx::Executor<'c, Database = DB>,
    for<'q> DB::Arguments<'q>: sqlx::IntoArguments<'q, DB>,
    for<'r> i64: sqlx::Decode<'r, DB> + sqlx::Type<DB>,
    for<'s> &'s str: sqlx::ColumnIndex<DB::Row>,
{
    let row = sqlx::query("SELECT COUNT(*) as count FROM test_items")
        .fetch_one(pool)
        .await
        .expect("Failed to count items");
    row.get::<i64, _>("count")
}

#[tokio::test]
async fn test_transaction_guard_commit_persists_changes() {
    with_test_pool!(|pool| {
        // Start a transaction and insert data
        let tx = pool.begin().await.expect("Failed to begin transaction");
        let mut guard = TransactionGuard::new(tx);

        sqlx::query("INSERT INTO test_items (name, value) VALUES ('item1', 100)")
            .execute(guard.executor().expect("Guard should have executor"))
            .await
            .expect("Failed to insert");

        // Commit the transaction
        guard.commit().await.expect("Commit should succeed");

        // Verify data was persisted
        assert_eq!(count_items(&pool).await, 1);
    });
}

#[tokio::test]
async fn test_transaction_guard_drop_without_commit_rolls_back() {
    with_test_pool!(|pool| {
        // Start a transaction and insert data, but don't commit
        {
            let tx = pool.begin().await.expect("Failed to begin transaction");
            let mut guard = TransactionGuard::new(tx);

            sqlx::query("INSERT INTO test_items (name, value) VALUES ('item2', 200)")
                .execute(guard.executor().expect("Guard should have executor"))
                .await
                .expect("Failed to insert");

            // Guard dropped here without commit - should rollback
        }

        // Verify data was NOT persisted (rolled back)
        assert_eq!(count_items(&pool).await, 0);
    });
}

#[tokio::test]
async fn test_transaction_guard_explicit_rollback() {
    with_test_pool!(|pool| {
        let tx = pool.begin().await.expect("Failed to begin transaction");
        let mut guard = TransactionGuard::new(tx);

        sqlx::query("INSERT INTO test_items (name, value) VALUES ('item3', 300)")
            .execute(guard.executor().expect("Guard should have executor"))
            .await
            .expect("Failed to insert");

        // Explicit rollback
        guard.rollback().await.expect("Rollback should succeed");

        // Verify data was NOT persisted
        assert_eq!(count_items(&pool).await, 0);
    });
}

#[tokio::test]
async fn test_transaction_guard_is_committed_before_commit() {
    with_test_pool!(|pool| {
        let tx = pool.begin().await.expect("Failed to begin transaction");
        let guard = TransactionGuard::new(tx);

        // Before commit, is_committed should be false
        assert!(!guard.is_committed());

        // Commit consumes self, so we can't check afterwards - just verify commit succeeds
        guard.commit().await.expect("Commit should succeed");
    });
}

#[tokio::test]
async fn test_transaction_guard_multiple_operations() {
    with_test_pool!(|pool| {
        let tx = pool.begin().await.expect("Failed to begin transaction");
        let mut guard = TransactionGuard::new(tx);

        // Multiple inserts in same transaction
        sqlx::query("INSERT INTO test_items (name, value) VALUES ('a', 1)")
            .execute(guard.executor().expect("Guard should have executor"))
            .await
            .expect("Failed to insert");

        sqlx::query("INSERT INTO test_items (name, value) VALUES ('b', 2)")
            .execute(guard.executor().expect("Guard should have executor"))
            .await
            .expect("Failed to insert");

        sqlx::query("INSERT INTO test_items (name, value) VALUES ('c', 3)")
            .execute(guard.executor().expect("Guard should have executor"))
            .await
            .expect("Failed to insert");

        guard.commit().await.expect("Commit should succeed");

        // All three items should be persisted
        assert_eq!(count_items(&pool).await, 3);
    });
}

#[tokio::test]
async fn test_transaction_guard_error_causes_rollback() {
    with_test_pool!(|pool| {
        // Insert one item first
        sqlx::query("INSERT INTO test_items (name, value) VALUES ('existing', 999)")
            .execute(&pool)
            .await
            .expect("Failed to insert initial item");

        assert_eq!(count_items(&pool).await, 1);

        // Try a transaction that will fail in the middle
        let result: Result<(), AppError> = async {
            let tx = pool
                .begin()
                .await
                .map_err(|e| AppError::database(e.to_string()))?;
            let mut guard = TransactionGuard::new(tx);

            sqlx::query("INSERT INTO test_items (name, value) VALUES ('new_item', 100)")
                .execute(guard.executor()?)
                .await
                .map_err(|e| AppError::database(e.to_string()))?;

            // Simulate an error condition
            return Err(AppError::internal("Simulated business logic error"));

            // This unreachable code would have committed
            #[allow(unreachable_code)]
            {
                guard.commit().await?;
                Ok(())
            }
        }
        .await;

        // The transaction should have failed
        assert!(result.is_err());

        // Only the original item should exist (new insert rolled back)
        assert_eq!(count_items(&pool).await, 1);
    });
}

#[tokio::test]
async fn test_retry_transaction_succeeds_first_try() {
    with_test_pool!(|pool| {
        let result = retry_transaction(
            || async {
                sqlx::query("INSERT INTO test_items (name, value) VALUES ('retry_test', 42)")
                    .execute(&pool)
                    .await
                    .map_err(|e| AppError::database(e.to_string()))?;
                Ok("success")
            },
            3,
        )
        .await;

        assert!(result.is_ok());
        assert_eq!(result.unwrap(), "success");
        assert_eq!(count_items(&pool).await, 1);
    });
}

#[tokio::test]
async fn test_retry_transaction_non_retryable_error_fails_immediately() {
    with_test_pool!(|pool| {
        // Create a unique constraint to trigger a non-retryable error
        sqlx::query(
            r"CREATE TABLE IF NOT EXISTS unique_test (
                id INTEGER PRIMARY KEY,
                unique_name TEXT UNIQUE NOT NULL
            )",
        )
        .execute(&pool)
        .await
        .expect("Failed to create unique_test table");

        // Insert initial row
        sqlx::query("INSERT INTO unique_test (id, unique_name) VALUES (1, 'duplicate')")
            .execute(&pool)
            .await
            .expect("Failed to insert initial row");

        let attempt_count = AtomicU32::new(0);

        let result = retry_transaction(
            || {
                attempt_count.fetch_add(1, Ordering::SeqCst);
                async {
                    // This will fail with a UNIQUE constraint violation
                    sqlx::query(
                        "INSERT INTO unique_test (id, unique_name) VALUES (2, 'duplicate')",
                    )
                    .execute(&pool)
                    .await
                    .map_err(|e| AppError::database(e.to_string()))?;
                    Ok(())
                }
            },
            5,
        )
        .await;

        // Should fail without retrying (constraint violation is not retryable)
        assert!(result.is_err());
        // Should only attempt once since constraint violations are not retryable
        assert_eq!(
            attempt_count.load(Ordering::SeqCst),
            1,
            "Non-retryable errors should not be retried"
        );
    });
}

#[tokio::test]
async fn test_transaction_guard_with_retry_pattern() {
    with_test_pool!(|pool| {
        let result = retry_transaction(
            || {
                let pool = pool.clone();
                async move {
                    let tx = pool
                        .begin()
                        .await
                        .map_err(|e| AppError::database(e.to_string()))?;
                    let mut guard = TransactionGuard::new(tx);

                    sqlx::query("INSERT INTO test_items (name, value) VALUES ('guarded', 777)")
                        .execute(guard.executor()?)
                        .await
                        .map_err(|e| AppError::database(e.to_string()))?;

                    sqlx::query("INSERT INTO test_items (name, value) VALUES ('guarded2', 888)")
                        .execute(guard.executor()?)
                        .await
                        .map_err(|e| AppError::database(e.to_string()))?;

                    guard.commit().await?;
                    Ok(2_i32)
                }
            },
            3,
        )
        .await;

        assert!(result.is_ok());
        assert_eq!(result.unwrap(), 2);
        assert_eq!(count_items(&pool).await, 2);
    });
}
