#!/usr/bin/env bash
# ABOUTME: Fixture test for check-lockfile-duplicates.sh — plants each split-lockfile shape and
# ABOUTME: proves the guard fires on it, then proves it stays quiet on a converged lockfile.
#
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 dravr.ai
#
# The guard runs inside bump lanes that push to main, so it cannot be exercised
# on a branch; this test is its only verification before it meets a real bump.
# Every case that matters is a fired one: a lockfile written the way cargo
# writes one, with one duplicate planted, must be refused and the refusal must
# name the crate and every version and source it holds. A guard only ever run
# on a clean tree proves nothing — it would report ✅ forever (carnet#328).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UNDER_TEST="$SCRIPT_DIR/check-lockfile-duplicates.sh"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

failures=0
pass() { echo "  ✅ $1"; }
fail() { echo "  ❌ $1"; failures=$((failures + 1)); }

# Output lands in a fixed file, not a variable: run_guard is called inside a
# command substitution, so any variable it sets dies with that subshell.
OUT="$(mktemp)"
WORK="$(mktemp -d)"
trap 'rm -rf "$OUT" "$WORK"' EXIT

run_guard() { # $1 = lockfile; echoes exit code, leaves output in $OUT
  local code=0
  "$UNDER_TEST" "$1" >"$OUT" 2>&1 || code=$?
  printf '%s\n' "$code"
}

expect() { # $1 = label, $2 = actual, $3 = wanted
  if [ "$2" = "$3" ]; then pass "$1"; else
    fail "$1 (exit $2, wanted $3)"; sed 's/^/       /' "$OUT"
  fi
}

# Every fixture starts from the same converged graph: three git-tag crates, two
# bare-named crates.io crates, the bare-named photograveur git crate, a
# workspace member, and a pair of `syn` versions that is legitimate in any real
# lockfile. A case plants exactly one extra block on top of this.
BASE="$WORK/base.lock"
cat > "$BASE" <<'LOCK'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "dravr-enforme"
version = "0.1.50"
source = "git+https://github.com/dravr-ai/dravr-enforme.git?tag=v0.1.50#30cea2d9c72499dc5f6e9782ae61758bc394913c"
dependencies = [
 "dravr-equilibre",
 "dravr-sciotte",
]

[[package]]
name = "dravr-equilibre"
version = "0.2.5"
source = "git+https://github.com/dravr-ai/dravr-equilibre.git?tag=v0.2.5#ba9941b31c175c5fda5e91f3b4615ffd556b4407"

[[package]]
name = "dravr-sciotte"
version = "0.9.2"
source = "git+https://github.com/dravr-ai/dravr-sciotte.git?tag=v0.9.2#57de9c725d435e4fd9e918459e5fe48c22d25fa1"

[[package]]
name = "dravr-tronc"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"

[[package]]
name = "embacle"
version = "0.25.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"

[[package]]
name = "embacle-tool-host"
version = "0.25.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2222222222222222222222222222222222222222222222222222222222222222"
dependencies = [
 "embacle",
]

[[package]]
name = "photograveur"
version = "0.1.6"
source = "git+https://github.com/dravr-ai/dravr-photograveur.git?tag=v0.1.6#857bedbbdcf3f4edf616f6fa6a767af938533b28"

[[package]]
name = "pierre_mcp_server"
version = "0.1.0"
dependencies = [
 "dravr-enforme",
 "photograveur",
 "syn 2.0.100",
]

[[package]]
name = "syn"
version = "1.0.109"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3333333333333333333333333333333333333333333333333333333333333333"

[[package]]
name = "syn"
version = "2.0.100"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "4444444444444444444444444444444444444444444444444444444444444444"

[[patch.unused]]
name = "dravr-canot"
version = "0.4.28"
source = "git+https://github.com/dravr-ai/dravr-canot.git?tag=v0.4.28#9d8c1739a800bb15d6d6b401176e300b8f2a8a76"
LOCK

plant() { # $1 = fixture path, then a heredoc on stdin with the extra block(s)
  cp "$BASE" "$1"
  { echo; cat; } >> "$1"
}

echo "check-lockfile-duplicates.sh"

# --- 1. converged: pass, and the count proves the parse saw every block --------
# `syn` at two versions is deliberately in the base: the gate is scoped to the
# ecosystem, and a legitimate transitive duplicate elsewhere must not fire it.
# The [[patch.unused]] block at the end must not be read as an eighth package.
code="$(run_guard "$BASE")"
expect "converged lockfile passes" "$code" 0
grep -q "7 dravr-ecosystem crate(s)" "$OUT" || fail "converged lockfile: expected 7 ecosystem crates counted, got: $(cat "$OUT")"

# --- 2. the carnet#323 shape: one crate at two git tags ------------------------
# enforme v0.1.49 pulled dravr-equilibre 0.2.5 while the platform pinned 0.2.4.
# Neither lane counted equilibre, so the split reached CI as E0053/E0308.
f="$WORK/two-tags.lock"
plant "$f" <<'LOCK'
[[package]]
name = "dravr-equilibre"
version = "0.2.4"
source = "git+https://github.com/dravr-ai/dravr-equilibre.git?tag=v0.2.4#a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9"
LOCK
code="$(run_guard "$f")"
expect "one crate at two git tags fails" "$code" 1
grep -q "dravr-equilibre resolves more than once" "$OUT" || fail "two tags: failure output must name the crate"
grep -q "0.2.4" "$OUT" || fail "two tags: failure output must name the old version"
grep -q "0.2.5" "$OUT" || fail "two tags: failure output must name the new version"
grep -q "^::error::" "$OUT" || fail "two tags: failure must surface as an Actions error annotation"

# --- 3. same version, two sources -----------------------------------------------
# A registry release and a git tag of the same version are two packages to
# cargo. The version strings are identical, so only the source tells them
# apart, and the refusal has to print it.
f="$WORK/two-sources.lock"
plant "$f" <<'LOCK'
[[package]]
name = "dravr-tronc"
version = "1.0.0"
source = "git+https://github.com/dravr-ai/dravr-tronc.git?tag=v1.0.0#f0e1d2c3b4a5968778695a4b3c2d1e0f11223344"
LOCK
code="$(run_guard "$f")"
expect "one version from two sources fails" "$code" 1
grep -q "dravr-tronc resolves more than once" "$OUT" || fail "two sources: failure output must name the crate"
grep -q "registry+https://github.com/rust-lang/crates.io-index" "$OUT" || fail "two sources: failure output must name the registry source"
grep -q "git+https://github.com/dravr-ai/dravr-tronc.git?tag=v1.0.0" "$OUT" || fail "two sources: failure output must name the git source"

# --- 4. a bare-named crates.io crate (prefix membership) ------------------------
# embacle ships from crates.io under its bare name; the `embacle` prefix is what
# admits it, exactly as ci-backend's cargo-tree gate matches it explicitly.
f="$WORK/embacle.lock"
plant "$f" <<'LOCK'
[[package]]
name = "embacle-tool-host"
version = "0.24.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5555555555555555555555555555555555555555555555555555555555555555"
LOCK
code="$(run_guard "$f")"
expect "embacle-tool-host at two versions fails" "$code" 1
grep -q "embacle-tool-host resolves more than once" "$OUT" || fail "embacle: failure output must name the crate"
grep -q "embacle resolves more than once" "$OUT" && fail "embacle: the bare crate was reported although only tool-host was split"

# --- 5. a bare-named dravr-ai git crate (source membership) ---------------------
# photograveur carries no dravr- prefix and is not embacle. Its source is what
# admits it; a name-only gate would let its lane push a split lockfile.
f="$WORK/photograveur.lock"
plant "$f" <<'LOCK'
[[package]]
name = "photograveur"
version = "0.1.7"
source = "git+https://github.com/dravr-ai/dravr-photograveur.git?tag=v0.1.7#99887766554433221100ffeeddccbbaa99887766"
LOCK
code="$(run_guard "$f")"
expect "photograveur at two tags fails" "$code" 1
grep -q "photograveur resolves more than once" "$OUT" || fail "photograveur: failure output must name the crate"
grep -q "0.1.6" "$OUT" || fail "photograveur: failure output must name the pinned tag"
grep -q "0.1.7" "$OUT" || fail "photograveur: failure output must name the pulled-in tag"

# --- 6. a workspace member shadowed by a git copy ------------------------------
# A path package has no `source` line. Vendoring a crate in-tree while a
# dependency still pulls it from git is two copies, and the refusal reports the
# path one as such rather than dropping the block for lacking a source.
f="$WORK/path-and-git.lock"
plant "$f" <<'LOCK'
[[package]]
name = "dravr-sciotte"
version = "0.9.2"
LOCK
code="$(run_guard "$f")"
expect "a path copy beside a git copy fails" "$code" 1
grep -q "dravr-sciotte resolves more than once" "$OUT" || fail "path copy: failure output must name the crate"
grep -qE "0\.9\.2  path$" "$OUT" || fail "path copy: failure output must report the workspace copy as path"

# --- 7. two splits at once: both named --------------------------------------------
# A tronc bump that leaves embacle behind splits two crates in one lockfile.
# The refusal lists every one, so the fix is one commit rather than two runs.
f="$WORK/two-splits.lock"
plant "$f" <<'LOCK'
[[package]]
name = "dravr-tronc"
version = "0.11.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "6666666666666666666666666666666666666666666666666666666666666666"

[[package]]
name = "embacle"
version = "0.24.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7777777777777777777777777777777777777777777777777777777777777777"
LOCK
code="$(run_guard "$f")"
expect "two split crates fail" "$code" 1
grep -q "dravr-tronc resolves more than once" "$OUT" || fail "two splits: dravr-tronc must be named"
grep -q "embacle resolves more than once" "$OUT" || fail "two splits: embacle must be named"
grep -q "embacle-tool-host resolves more than once" "$OUT" && fail "two splits: embacle-tool-host was named although it is not split"

# --- 8. nothing to scan: fail, never a vacuous pass ------------------------------
f="$WORK/no-ecosystem.lock"
cat > "$f" <<'LOCK'
version = 4

[[package]]
name = "syn"
version = "2.0.100"
source = "registry+https://github.com/rust-lang/crates.io-index"
LOCK
expect "a lockfile with no ecosystem crate fails rather than passing vacuously" "$(run_guard "$f")" 1

# --- 9. unreadable path: misuse, distinct from a verdict -------------------------
expect "a missing lockfile is misuse (exit 2)" "$(run_guard "$WORK/does-not-exist.lock")" 2

# --- 10. the real lockfile --------------------------------------------------------
# The tree this test ships in holds one entry per ecosystem crate. If this case
# ever fails, main's lockfile is split and the output above names the crate.
code="$(run_guard "$REPO_ROOT/Cargo.lock")"
expect "the repository's own Cargo.lock is converged" "$code" 0
grep -qE "[0-9]+ dravr-ecosystem crate\(s\)" "$OUT" || fail "real lockfile: the parse reported no ecosystem count"

echo
if [ "$failures" -gt 0 ]; then
  echo "❌ $failures case(s) failed"
  exit 1
fi
echo "✅ all cases passed"
