#!/bin/bash
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 dravr.ai
# ABOUTME: Compile-free static check that platform code stays in sync with the
# ABOUTME: dravr-contremaitre catalogues (locales, notify events, MCP tool list).

# WHY THIS EXISTS
# ---------------
# The integration tests that police platform<->contremaitre coupling
# (contremaitre_test, notify_catalogue_test, messaging_locale_test) live in
# pierre-server/tests. They are also wired into the per-push `contremaitre-sync`
# job in ci-backend.yml, but that job costs a Rust compile; this script is the
# grep-only pre-push tier that catches the same drift in seconds, before the
# push, with no compile at all.
#
# Covered:
#   1. Locale invariant — every messaging-string key ships all 5 locales
#      (fr/en/es/de/pt). Mirrors contremaitre_test
#      test_messaging_registry_seeds_all_compiled_locales (entry == keys * 5).
#   2. Notify catalogue — every info!(target:"notify", event="X") emitted in
#      platform src exists as a key in contremaitre's notify-events.yaml.
#      Mirrors notify_catalogue_test.
#   3. MCP tool list — the tool names in src match all three of their mirrors:
#      EXPECTED_TOOLS (contremaitre_test), the hardcoded count assertion
#      (configuration_mcp_integration_test), and the generated TS SDK types
#      (packages/mcp-types/src/tools.ts, whose staleness reds CI: TypeScript SDK).
#   4. Framing — the shipped tool descriptions and coach prompts carry no
#      retired ACWR-as-injury-risk or absolute-TSB framing.
#   5. Tool overlays — every tools/<name>.yaml in the pinned rev names a tool the
#      registry actually registers, so no overlay is keyed to nothing.
#   6. String copy — packages/i18n/src/locales/<l>/translation.json is
#      byte-identical to the pinned rev's strings/<l>.json. Strings are authored
#      in dravr-contremaitre; the platform copy is regenerated by the pin bump.
#   7. Overlay parameters — every tools/<name>.yaml parameter names a property
#      the Rust schema declares, so no parameter description is written and
#      never served.
#   8. Pin ownership — a branch never moves the contremaitre pin, its
#      Cargo.lock entry or the string copy; only contremaitre-bump.yml does, on
#      main (carnet#826).
#
# Contremaitre is upstream, and every check above is one-directional so that a
# change authored there first is valid on its own: strings, server-rendered
# keys, notify events and prompts land in dravr-contremaitre, the bump lane
# moves the pin within minutes, and the platform code that reads them follows.
# Tools go the other way — the platform registers the tool, then contremaitre
# overlays its description. Removals reverse both orders.
#
# --contremaitre-root DIR runs the same checks against an unpinned contremaitre
# tree instead of the pinned one. dravr-contremaitre's pre-push gate calls it on
# an export of platform main, so a contremaitre push that would wedge the bump
# lane fails on the author's machine before it lands. Checks 6 and 8 are about
# the platform's own pin and are skipped in that mode.
#
# Checks 5 and 7 are one-directional, and the asymmetry is the contract: tool
# overlays are SPARSE. A tool with no yaml keeps its compiled-in description;
# only an overlay naming something that does not exist is a failure, because
# that override reaches nothing and says nothing when it does.
#
# Known blind spot: an event or tool whose name is built at runtime rather than
# written as a literal is invisible to a static scan. Check 3 defends against
# that through tool_schema_properties.py, which asserts one literal name per
# tool_definition( call site and fails loudly if the assumption ever breaks.
# See AGENTS.md.

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"

CM_OVERRIDE=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --contremaitre-root)
            if [[ -z "${2:-}" ]] || [[ ! -d "$2/strings" ]]; then
                echo -e "${RED}❌ --contremaitre-root needs a dravr-contremaitre tree (one with strings/), got '${2:-}'.${NC}"
                exit 2
            fi
            CM_OVERRIDE="$( cd "$2" && pwd )/"
            shift 2
            ;;
        *)
            echo -e "${RED}❌ unknown argument: $1 (usage: $0 [--contremaitre-root DIR])${NC}"
            exit 2
            ;;
    esac
done

cd "$PROJECT_ROOT"

echo -e "${BLUE}==== Contremaitre Coupling Sync (static) ====${NC}"

FAILED=false

# The contremaitre tree every check below reads: the pinned rev (Cargo.lock,
# through cargo metadata), else a sibling checkout, else the tree
# --contremaitre-root names. Resolved once, so no two checks can read two
# different revs.
MANIFEST=""
CM_ROOT=""
if [[ -n "$CM_OVERRIDE" ]]; then
    CM_ROOT="$CM_OVERRIDE"
    echo -e "${BLUE}Reading the unpinned contremaitre tree at ${CM_ROOT}${NC}"
else
    # The list comprehension avoids a `((` inside `$( )`, which stock macOS bash
    # (3.2) parses as the start of an arithmetic expansion and then rejects.
    MANIFEST="$(cargo metadata --format-version 1 2>/dev/null \
        | python3 -c 'import json,sys; d=json.load(sys.stdin); m=[p["manifest_path"] for p in d["packages"] if p["name"]=="dravr-contremaitre"]; print(m[0] if m else "")' 2>/dev/null || true)"
    if [[ -n "$MANIFEST" && -d "${MANIFEST%Cargo.toml}tools" ]]; then
        CM_ROOT="${MANIFEST%Cargo.toml}"
    elif [[ -d "../dravr-contremaitre/tools" ]]; then
        CM_ROOT="../dravr-contremaitre/"
    fi
fi

# ---------------------------------------------------------------------------
# Check 1: the string catalogue ships every key in all 5 locales
# ---------------------------------------------------------------------------
# The catalogue is the five nested packages/i18n/src/locales/<l>/translation.json
# files: the messaging-strings registry seeds from them (include_str!), both
# clients embed them, GET /api/i18n/{locale} serves them, contremaitre overlays
# them. One key set across the five files is the invariant that used to be
# `entries == keys × 5` over the Rust COMPILED_IN table.
#
# A key is rendered by exactly one side: server-rendered keys take positional
# {0} placeholders, client keys take i18next {{name}} placeholders. Which keys
# are server-rendered is declared in contremaitre, beside the text, in
# strings/server-rendered-keys.txt — so contremaitre's own tests hold every
# string to its side and a server string can land there first. The platform's
# half is one-directional: every `KEY_*` literal declared in the contremaitre
# crate must be listed there. A listed key no KEY_* reads yet is not drift; it
# is a string the platform has not started rendering (carnet#826).
#
# With --contremaitre-root the catalogue is read from that tree's
# strings/<l>.json rather than the platform's copy, which only the bump lane
# rewrites.
REGISTRY_SRC="crates/pierre-contremaitre/src"
LOCALE_LIST_RS="crates/pierre-core/src/models/user.rs"
LOCALE_LIST_TS="packages/i18n/src/config.ts"
if [[ -n "$CM_OVERRIDE" ]]; then
    CATALOGUE_FILE="${CM_ROOT}strings/{locale}.json"
else
    CATALOGUE_FILE="packages/i18n/src/locales/{locale}/translation.json"
fi
SERVER_KEYS_FILE="${CM_ROOT}strings/server-rendered-keys.txt"

if [[ ! -d "$REGISTRY_SRC" ]] || [[ ! -f "${CATALOGUE_FILE/\{locale\}/fr}" ]]; then
    echo -e "${RED}❌ Catalogue or registry source not found — this check is stale.${NC}"
    FAILED=true
elif [[ -z "$CM_ROOT" ]] || [[ ! -f "$SERVER_KEYS_FILE" ]]; then
    # Fail closed, like Check 6: without the list no key can be classified, and
    # a check that classifies nothing reads exactly like a pass.
    echo -e "${RED}❌ Server-rendered key list not found${CM_ROOT:+ at ${SERVER_KEYS_FILE}}.${NC}"
    echo -e "${YELLOW}   It is dravr-contremaitre strings/server-rendered-keys.txt in the pinned rev. Resolve the pin${NC}"
    echo -e "${YELLOW}   (cargo fetch) — or, if the pinned rev predates the list, rebase onto main for the bot's bump.${NC}"
    FAILED=true
else
    # The locale list is read, never spelled here: SUPPORTED_LOCALES in
    # pierre-core is the one list, and the clients' SUPPORTED_LANGUAGES must
    # agree with it in order (the first entry is the default locale on both
    # sides). Parsed in shell rather than in the Python below, which stock
    # macOS bash (3.2) mis-parses when the heredoc body grows.
    LOCALES_RS="$(sed -nE 's/.*SUPPORTED_LOCALES: \[&str; [0-9]+\] = \[(.*)\];.*/\1/p' "$LOCALE_LIST_RS" | tr -d '" ')"
    LOCALES_TS="$(sed -nE 's/.*SUPPORTED_LANGUAGES[^=]*= *\[([^]]*)\].*/\1/p' "$LOCALE_LIST_TS" | tr -d "' ")"
    if [[ -z "$LOCALES_RS" ]]; then
        echo -e "${RED}❌ could not read SUPPORTED_LOCALES from $LOCALE_LIST_RS${NC}"
        FAILED=true
    elif [[ "$LOCALES_RS" != "$LOCALES_TS" ]]; then
        echo -e "${RED}❌ Locale drift: the clients speak [$LOCALES_TS] but the platform speaks [$LOCALES_RS] — one list, same order.${NC}"
        FAILED=true
    fi

    if CATALOGUE_REPORT="$(python3 - "$CATALOGUE_FILE" "$REGISTRY_SRC" "$LOCALES_RS" "$SERVER_KEYS_FILE" <<'PY'
import json, pathlib, re, sys

catalogue_file, registry_src, locale_csv, server_keys_file = sys.argv[1:5]
locales = [code for code in locale_csv.split(",") if code]


def flatten(tree, prefix=""):
    for key, value in tree.items():
        dotted = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            yield from flatten(value, dotted)
        else:
            yield dotted, value


trees = {}
for locale in locales:
    with open(catalogue_file.replace("{locale}", locale), encoding="utf-8") as fh:
        trees[locale] = dict(flatten(json.load(fh)))

reference = set(trees["en"])
problems = []
for locale in locales:
    keys = set(trees[locale])
    problems += [f"{locale} is missing {k}" for k in sorted(reference - keys)]
    problems += [f"{locale} has an extra key {k}" for k in sorted(keys - reference)]

with open(server_keys_file, encoding="utf-8") as fh:
    server_keys = {line.strip() for line in fh if line.strip() and not line.lstrip().startswith("#")}
problems += [f"server-rendered-keys.txt lists {k} but the catalogue has no such key" for k in sorted(server_keys - reference)]

source = "\n".join(
    path.read_text(encoding="utf-8") for path in sorted(pathlib.Path(registry_src).rglob("*.rs"))
)
registry_keys = set(re.findall(r'^pub const KEY_[A-Z0-9_]+: &str =\s*"([^"]+)"', source, re.M | re.S))
problems += [
    f"registry declares {k} but contremaitre does not list it in strings/server-rendered-keys.txt"
    for k in sorted(registry_keys - server_keys)
]

positional = re.compile(r"\{\d+\}")
for locale in locales:
    for key, value in trees[locale].items():
        if key in server_keys and "{{" in value:
            problems.append(f"{locale} {key}: a server-rendered key must use positional {{0}} placeholders, not {{{{name}}}}")
        elif key not in server_keys and positional.search(value):
            problems.append(f"{locale} {key}: a client-rendered key must use {{{{name}}}} placeholders, not positional {{0}}")

print(f"{len(reference)} keys × {len(locales)} locales, {len(server_keys)} server-rendered, {len(registry_keys)} read by KEY_*")
if problems:
    print("\n".join(problems[:40]))
    if len(problems) > 40:
        print(f"... and {len(problems) - 40} more")
    sys.exit(1)
PY
)"; then
        echo -e "${GREEN}✅ Catalogue invariant: ${CATALOGUE_REPORT}, every key in all 5 locales.${NC}"
    else
        echo -e "${RED}❌ Catalogue drift:${NC}"
        printf '%s\n' "$CATALOGUE_REPORT" | sed 's/^/   /'
        echo -e "${YELLOW}   Every key ships in fr/en/es/de/pt, and every KEY_* under ${REGISTRY_SRC} names a key${NC}"
        echo -e "${YELLOW}   dravr-contremaitre lists in strings/server-rendered-keys.txt. A new server string lands${NC}"
        echo -e "${YELLOW}   there first; rebase onto main once the bump lane has moved the pin to it.${NC}"
        FAILED=true
    fi
fi

# ---------------------------------------------------------------------------
# Check 2: notify events emitted in src must be catalogued in notify-events.yaml
# ---------------------------------------------------------------------------
# The catalogue is the resolved contremaitre tree's; warn-skip if unresolvable
# so an offline machine is not blocked from pushing.
YAML=""
if [[ -n "$CM_ROOT" && -f "${CM_ROOT}schemas/notify-events.yaml" ]]; then
    YAML="${CM_ROOT}schemas/notify-events.yaml"
fi

if [[ -z "$YAML" ]]; then
    echo -e "${YELLOW}⚠️  notify-events.yaml could not be resolved (offline?) — skipping the notify check.${NC}"
else
    CATALOGUED="$(grep -E '^\s*- name:' "$YAML" | sed -E 's/.*- name:[[:space:]]*//' | tr -d ' "' | sort -u)"
    # Emitted events: each .rs under crates/*/src (not tests) that targets
    # "notify"; grab event = "literal" within a window around the target line.
    # Dynamically-built (non-literal) event names are a known blind spot.
    EMITTED="$(grep -rl 'target: "notify"' crates/*/src 2>/dev/null | grep -v '/tests/' \
        | while IFS= read -r f; do
            grep -B2 -A10 'target: "notify"' "$f" \
                | grep -oE 'event[[:space:]]*=[[:space:]]*"[^"]+"' \
                | sed -E 's/.*"([^"]+)".*/\1/'
          done | sort -u || true)"
    DRIFT="$(comm -23 <(printf '%s\n' "$EMITTED" | grep -v '^$') <(printf '%s\n' "$CATALOGUED" | grep -v '^$') || true)"
    if [[ -n "$DRIFT" ]]; then
        echo -e "${RED}❌ Notify catalogue drift: event(s) emitted in src but absent from notify-events.yaml:${NC}"
        printf '%s\n' "$DRIFT" | sed 's/^/   /'
        echo -e "${YELLOW}   Register the event in dravr-contremaitre notify-events.yaml (or reuse an existing one),${NC}"
        echo -e "${YELLOW}   then bump the contremaitre rev — else notify_catalogue_test reds main post-merge.${NC}"
        FAILED=true
    else
        EMIT_COUNT="$(printf '%s\n' "$EMITTED" | grep -c . || true)"
        echo -e "${GREEN}✅ Notify catalogue: all ${EMIT_COUNT} emitted events are catalogued.${NC}"
    fi
fi

# ---------------------------------------------------------------------------
# Check 3: MCP tool list vs its three mirrors
# ---------------------------------------------------------------------------
# Every McpTool::definition() builds its Tool through
# tool_definition("<name>", ...) (pierre-tool-runtime/src/conversions.rs), so the
# names ARE literals at a greppable call site and the full set is enumerable
# without compiling. The names come from scripts/ci/tool_schema_properties.py,
# the one enumeration of the registry — Check 7 and check-declared-parameters.sh
# attribute properties with the same scan — and so does the proof of its
# completeness: it raises when a call site's name is not a readable literal. The
# one premise added here is the one only a name list needs: no two call sites
# register the same name.
EXPECTED_FILE="crates/pierre-server/tests/contremaitre_test.rs"
COUNT_FILE="crates/pierre-server/tests/configuration_mcp_integration_test.rs"
TS_FILE="packages/mcp-types/src/tools.ts"

# Whether SRC_TOOLS below holds the complete registered set. Checks 5 and 7
# compare against it and must not run on a truncated scan.
TOOL_SCAN_COMPLETE=false

if ! TOOL_SCAN="$(python3 - <<'PYTOOLS'
import sys

sys.path.insert(0, "scripts/ci")
import tool_schema_properties as tsp

try:
    tools, stats = tsp.scan()
except tsp.ScanError as exc:
    print(f"SCAN_UNSOUND {exc}")
    raise SystemExit(0)
if stats["call_sites"] != len(tools):
    print(
        f"SCAN_UNSOUND {stats['call_sites']} tool_definition( call site(s) register "
        f"{len(tools)} distinct name(s), so a name is registered twice"
    )
    raise SystemExit(0)
print("\n".join(tools))
PYTOOLS
)"; then
    echo -e "${RED}❌ Tool scan could not run (scripts/ci/tool_schema_properties.py).${NC}"
    FAILED=true
else
    if [[ "$TOOL_SCAN" == SCAN_UNSOUND* ]]; then
        # The scan's own assumption broke. Fail loudly rather than compare a
        # silently-truncated set, which would read as "all tools in sync".
        echo -e "${RED}❌ Tool scan incomplete: ${TOOL_SCAN#SCAN_UNSOUND }${NC}"
        echo -e "${YELLOW}   This static scan can no longer stand behind the tool list. Fix the site named${NC}"
        echo -e "${YELLOW}   above, or extend tool_schema_properties.py — never ignore it.${NC}"
        FAILED=true
    else
        SRC_TOOLS="$(printf '%s\n' "$TOOL_SCAN" | sort -u)"
        SRC_COUNT="$(printf '%s\n' "$SRC_TOOLS" | grep -c . || true)"
        TOOL_SCAN_COMPLETE=true
        TOOL_DRIFT=false

        # 3a. EXPECTED_TOOLS in contremaitre_test.rs
        EXPECTED_LIST="$(awk '/EXPECTED_TOOLS/{f=1} f{print} f&&/^\];/{exit}' "$EXPECTED_FILE" 2>/dev/null \
            | grep -oE '"[a-z0-9_]+"' | tr -d '"' | sort -u || true)"
        if [[ -z "$EXPECTED_LIST" ]]; then
            echo -e "${RED}❌ Could not parse EXPECTED_TOOLS in ${EXPECTED_FILE} — structure changed; update this check.${NC}"
            TOOL_DRIFT=true
        else
            UNLISTED="$(comm -23 <(printf '%s\n' "$SRC_TOOLS") <(printf '%s\n' "$EXPECTED_LIST") || true)"
            PHANTOM="$(comm -13 <(printf '%s\n' "$SRC_TOOLS") <(printf '%s\n' "$EXPECTED_LIST") || true)"
            if [[ -n "$UNLISTED" ]]; then
                echo -e "${RED}❌ Tool drift: registered in src but absent from EXPECTED_TOOLS:${NC}"
                printf '%s\n' "$UNLISTED" | sed 's/^/   /'
                TOOL_DRIFT=true
            fi
            if [[ -n "$PHANTOM" ]]; then
                echo -e "${RED}❌ Tool drift: listed in EXPECTED_TOOLS but no longer registered in src:${NC}"
                printf '%s\n' "$PHANTOM" | sed 's/^/   /'
                TOOL_DRIFT=true
            fi

            # Order, not just membership. contremaitre_test asserts EXPECTED_TOOLS
            # is sorted, and Rust sorts &str by bytes: '_' (0x5F) lands before any
            # lowercase letter, so search_agent_store precedes search_agents. The
            # set comparison above pipes through `sort -u` and cannot see this, and
            # a hand-inserted name reads as correct to every human alphabet.
            EXPECTED_ORDER="$(awk '/EXPECTED_TOOLS/{f=1} f{print} f&&/^\];/{exit}' "$EXPECTED_FILE" 2>/dev/null \
                | grep -oE '"[a-z0-9_]+"' | tr -d '"' || true)"
            if [[ -n "$EXPECTED_ORDER" ]] \
               && ! diff -q <(printf '%s\n' "$EXPECTED_ORDER") \
                            <(printf '%s\n' "$EXPECTED_ORDER" | LC_ALL=C sort) >/dev/null; then
                echo -e "${RED}❌ EXPECTED_TOOLS is not in byte order — test_expected_tools_list_is_sorted will fail:${NC}"
                diff <(printf '%s\n' "$EXPECTED_ORDER") \
                     <(printf '%s\n' "$EXPECTED_ORDER" | LC_ALL=C sort) | sed 's/^/   /' | head -12
                TOOL_DRIFT=true
            fi
        fi

        # 3b. hardcoded total in configuration_mcp_integration_test.rs
        ASSERTED="$(grep -oE 'assert_eq!\([[:space:]]*tools\.len\(\),[[:space:]]*[0-9]+' "$COUNT_FILE" 2>/dev/null \
            | grep -oE '[0-9]+$' | sort -u || true)"
        ASSERT_LINES="$(printf '%s\n' "$ASSERTED" | grep -c . || true)"
        if [[ "$ASSERT_LINES" -ne 1 ]]; then
            echo -e "${RED}❌ Expected exactly one tools.len() assertion in ${COUNT_FILE}, found ${ASSERT_LINES} distinct value(s) — update this check.${NC}"
            TOOL_DRIFT=true
        elif [[ "$ASSERTED" -ne "$SRC_COUNT" ]]; then
            echo -e "${RED}❌ Tool count drift: src registers ${SRC_COUNT} tools, ${COUNT_FILE} asserts ${ASSERTED}.${NC}"
            TOOL_DRIFT=true
        fi

        # 3c. generated TS SDK types — stale types red CI: TypeScript SDK
        if [[ ! -f "$TS_FILE" ]]; then
            echo -e "${RED}❌ ${TS_FILE} not found — this check is stale.${NC}"
            TOOL_DRIFT=true
        else
            TS_TOOLS="$(grep -oE '"[a-z0-9_]+"' "$TS_FILE" | tr -d '"' | sort -u || true)"
            TS_HEADER="$(grep -oE '^// Tool count: [0-9]+' "$TS_FILE" | grep -oE '[0-9]+' || true)"
            TS_DIFF="$(comm -3 <(printf '%s\n' "$SRC_TOOLS") <(printf '%s\n' "$TS_TOOLS") || true)"
            if [[ -n "$TS_DIFF" || "$TS_HEADER" != "$SRC_COUNT" ]]; then
                echo -e "${RED}❌ SDK type drift: ${TS_FILE} does not match the ${SRC_COUNT} tools in src (header says '${TS_HEADER}').${NC}"
                [[ -n "$TS_DIFF" ]] && printf '%s\n' "$TS_DIFF" | sed 's/^/   /'
                echo -e "${YELLOW}   Regenerate against a running server: cd packages/mcp-types && bun run generate${NC}"
                TOOL_DRIFT=true
            fi
        fi

        if [[ "$TOOL_DRIFT" == "true" ]]; then
            echo -e "${YELLOW}   A new McpTool must land with EXPECTED_TOOLS (kept sorted), the count assertion,${NC}"
            echo -e "${YELLOW}   and regenerated SDK types in the SAME change — else main reds post-merge.${NC}"
            FAILED=true
        else
            echo -e "${GREEN}✅ MCP tool list: ${SRC_COUNT} tools match EXPECTED_TOOLS, the count assertion, and the SDK types.${NC}"
        fi
    fi
fi

# ---------------------------------------------------------------------------
# Check 4: the shipped contremaitre catalogues carry no retired ACWR framing
# ---------------------------------------------------------------------------
# Tool descriptions and persona prompts reach the model through the runtime
# sync, not through include_str!, so no Rust test can see them: a test that
# reads registry_builtin::get_tools() inspects the compiled-in fallback that
# ToolRegistry::build_schema overwrites. This is the only gate that reads what
# actually ships. It bans the framings, not the framework name — "ACWR →
# Gabbett" as an attribution is fine, and the coach prompt legitimately explains
# what "the retired injury-prediction use" was.
if [[ -z "$CM_ROOT" ]]; then
    echo -e "${YELLOW}⚠️  contremaitre corpus could not be resolved (offline?) — skipping the framing check.${NC}"
else
    # Couple the injury token to a load token before flagging: a strength coach
    # citing Lauersen on resistance training reducing injury risk, and a mobility
    # coach on warm-ups, are unrelated to the ratio. Lines that *forbid* the
    # framing ("never present it as an injury risk") are excluded too.
    FRAMING_HITS="$(python3 - "$CM_ROOT" <<'PYCHECK'
import json, pathlib, re, sys
root = pathlib.Path(sys.argv[1])
INJURY = re.compile(r"injury risk|injury probabilit|risque de blessure|probabilit\w* de blessure", re.I)
LOAD = re.compile(r"acwr|load spike|load increase|acute:chronic|charge aigu|pic de charge|hausses soudaines", re.I)
NEGATED = re.compile(r"never|not present|jamais|retired|retir\u00e9|\bpas\b", re.I)
GREEN = re.compile(r"green band|bande verte", re.I)
ABS_TSB = re.compile(r"TSB\s*[<>\u2264\u2265]\s*[-\u2212+]?\d", re.I)
hits = []

def classify(text):
    if INJURY.search(text) and LOAD.search(text) and not NEGATED.search(text):
        return "ACWR presented as injury risk"
    if GREEN.search(text):
        return "red/green safety verdict"
    if ABS_TSB.search(text):
        return "absolute TSB band (use % of CTL)"
    return None

# The personas directory is being renamed coaches -> agents in
# dravr-contremaitre, and the two repositories deploy independently, so either
# name may be the one on disk. Accept both -- and refuse to pass when neither
# is there, because a framing scan that walked no persona file reports exactly
# the same green as one that walked them all and found nothing.
PERSONAS = ("prompts/coaches", "prompts/agents")
if not any((root / sub).is_dir() for sub in PERSONAS):
    print(f"SCAN-INCOMPLETE: no personas directory at {' or '.join(PERSONAS)}", file=sys.stderr)
    sys.exit(2)
for sub in ("tools", "prompts/personas", *PERSONAS):
    d = root / sub
    if not d.is_dir():
        continue
    for f in sorted(d.rglob("*")):
        if f.suffix not in (".md", ".yaml", ".yml"):
            continue
        for n, line in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
            why = classify(line)
            if why:
                hits.append(f"{f}:{n}: [{why}] {line.strip()[:160]}")

# The label and prompt of a use case are offered to the athlete as their own words
# and sent to the model as their question (carnet#828), so they answer to the
# same framing as a prompt -- in every locale.
def leaves(node, path):
    if isinstance(node, dict):
        for key, value in node.items():
            yield from leaves(value, f"{path}.{key}")
    elif isinstance(node, str):
        yield path, node

for f in sorted((root / "strings").glob("*.json")):
    catalogue = json.loads(f.read_text(encoding="utf-8"))
    for key, value in leaves(catalogue.get("use_cases", {}), "use_cases"):
        why = classify(value)
        if why:
            hits.append(f"{f}:{key}: [{why}] {value.strip()[:160]}")
print("\n".join(hits))
PYCHECK
)"

    if [[ -n "$FRAMING_HITS" ]]; then
        echo -e "${RED}❌ Retired ACWR/TSB framing in the shipped contremaitre catalogues:${NC}"
        echo -e "$FRAMING_HITS"
        echo -e "${YELLOW}   Present ACWR as magnitude against the 28-day baseline, never injury risk or a${NC}"
        echo -e "${YELLOW}   red/green verdict, and band TSB as a share of CTL (registre#26).${NC}"
        FAILED=true
    else
        echo -e "${GREEN}✅ Contremaitre catalogues carry no retired ACWR/TSB framing.${NC}"
    fi
fi

# ---------------------------------------------------------------------------
# Check 5: every tools/<name>.yaml names a tool the registry registers
# ---------------------------------------------------------------------------
# A tool description overlay is addressed by tool name end to end: manifest.json
# keys its `tools` map by the file stem, sync stores the parsed overlay under
# that key, and ToolRegistry::build_schema looks the running tool's own name up
# in the registry. A stem matching no registered tool is therefore a dead
# overlay — the lookup misses, the compiled-in description ships, and nothing
# anywhere reports it: `HashMap::get` returning None is not an error.
#
# One direction only. contremaitre does not ship a yaml for every tool, and is
# not meant to: a tool with no overlay keeps its compiled-in description, which
# is the normal state for most of the registry. The failure is a yaml with no
# tool.
if [[ "$TOOL_SCAN_COMPLETE" != "true" ]]; then
    echo -e "${YELLOW}⚠️  Tool overlay check skipped: the tool scan above did not resolve every name.${NC}"
elif [[ -z "$CM_ROOT" ]]; then
    echo -e "${YELLOW}⚠️  contremaitre corpus could not be resolved (offline?) — skipping the tool overlay check.${NC}"
else
    OVERLAY_STEMS="$(find "${CM_ROOT}tools" -maxdepth 1 -type f -name '*.yaml' 2>/dev/null \
        | sed -E 's#.*/##; s#\.yaml$##' | sort -u || true)"
    if [[ -z "$OVERLAY_STEMS" ]]; then
        # The directory is what made CM_ROOT resolve, so an empty scan means the
        # overlays moved or changed shape. Fail rather than report "in sync".
        echo -e "${RED}❌ Overlay scan incomplete: ${CM_ROOT}tools holds no *.yaml.${NC}"
        echo -e "${YELLOW}   The overlays moved or changed extension, so this check can no longer see them.${NC}"
        echo -e "${YELLOW}   Point it at the new layout — never ignore it.${NC}"
        FAILED=true
    else
        DEAD_OVERLAYS="$(comm -13 <(printf '%s\n' "$SRC_TOOLS") <(printf '%s\n' "$OVERLAY_STEMS") || true)"
        if [[ -n "$DEAD_OVERLAYS" ]]; then
            echo -e "${RED}❌ Dead tool overlay(s): tools/<name>.yaml whose stem matches no registered tool:${NC}"
            printf '%s\n' "$DEAD_OVERLAYS" | sed 's/^/   /'
            echo -e "${YELLOW}   The overlay is keyed by tool name, so these reach no schema: the compiled-in${NC}"
            echo -e "${YELLOW}   description ships instead and the miss is silent. Rename the yaml to the tool's${NC}"
            echo -e "${YELLOW}   name in dravr-contremaitre, or delete it if the tool is gone.${NC}"
            FAILED=true
        else
            OVERLAY_COUNT="$(printf '%s\n' "$OVERLAY_STEMS" | grep -c . || true)"
            echo -e "${GREEN}✅ Tool overlays: all ${OVERLAY_COUNT} tools/*.yaml name a registered tool.${NC}"
        fi
    fi
fi

# ---------------------------------------------------------------------------
# Check 6: the i18n catalogue is byte-identical to the pinned strings/
# ---------------------------------------------------------------------------
# dravr-contremaitre is where every string is authored; packages/i18n holds a
# copy of the pinned rev's strings/<locale>.json, regenerated by
# scripts/ci/sync-contremaitre-fallback.sh on every pin bump. A string edited in
# the copy first is the failure this refuses: the next bump reverts it, and the
# runtime overlay already serves contremaitre's text in production, so a
# platform-only edit ships nowhere but the cold-start fallback (carnet#593).
#
# Fail-closed on every axis: an unresolved pin, a missing checkout, a locale on
# one side only or a checkout with no strings/ each fail, and the verdict is
# the script's exit status AND its success marker — never the absence of a
# finding.
SYNC_SCRIPT="scripts/ci/sync-contremaitre-fallback.sh"
if [[ -n "$CM_OVERRIDE" ]]; then
    echo -e "${BLUE}ℹ️  String copy skipped: --contremaitre-root reads an unpinned tree; the bump lane writes the copy.${NC}"
elif [[ ! -x "$SYNC_SCRIPT" ]]; then
    echo -e "${RED}❌ String copy check cannot run: ${SYNC_SCRIPT} is missing.${NC}"
    FAILED=true
elif ! STRINGS_REPORT="$("$SYNC_SCRIPT" --check 2>&1)"; then
    echo -e "${RED}❌ packages/i18n is not the pinned contremaitre strings/, byte for byte:${NC}"
    printf '%s\n' "$STRINGS_REPORT" | sed 's/^/   /'
    echo -e "${YELLOW}   Strings are authored in dravr-contremaitre strings/<locale>.json. Change them there,${NC}"
    echo -e "${YELLOW}   bump the pin, and run ${SYNC_SCRIPT} — never edit the platform copy.${NC}"
    FAILED=true
elif ! grep -qF "byte-identical to dravr-contremaitre" <<<"$STRINGS_REPORT"; then
    echo -e "${RED}❌ String copy check passed without reporting a comparison:${NC}"
    printf '%s\n' "$STRINGS_REPORT" | sed 's/^/   /'
    FAILED=true
else
    echo -e "${GREEN}${STRINGS_REPORT}${NC}"
fi

# ---------------------------------------------------------------------------
# Check 7: every tools/<name>.yaml parameter names a property the schema declares
# ---------------------------------------------------------------------------
# The parameter-level sibling of Check 5, and it fails the same way: silently.
# ToolRegistry::build_schema overlays a parameter description with
# `props.get_mut(param_name)` and no else arm, so an entry naming a property the
# Rust schema does not declare is dropped without a warning. The operator writes
# the text, the yaml parses, the sync succeeds, and nothing ever serves it.
#
# Not hypothetical: at rev 37e2ab2 three of the four analytics overlays declared
# a `days` parameter — `calculate_fitness_score` had never had one in Rust at
# all — and all three had been dead since they were written (registre#420).
#
# One direction only, like Check 5. An overlay need not describe every property;
# a property with no override keeps its compiled-in description. The failure is
# an override with no property.
if [[ "$TOOL_SCAN_COMPLETE" != "true" ]]; then
    echo -e "${YELLOW}⚠️  Overlay parameter check skipped: the tool scan above did not resolve every name.${NC}"
elif [[ -z "$CM_ROOT" ]]; then
    echo -e "${YELLOW}⚠️  contremaitre corpus could not be resolved (offline?) — skipping the overlay parameter check.${NC}"
else
    if PARAM_REPORT="$(python3 - "$CM_ROOT" <<'PYPARAM'
import glob
import os
import re
import sys

cm_root = sys.argv[1]
tools_dir = os.path.join(cm_root, "tools")

# Rust side: the shared attribution, also used by check-declared-parameters.sh
# (Tier 1i), which asks the opposite question — this is "declared in the yaml
# overlay, not in the schema", that one is "refused for something never
# offered". The helper asserts its own premise: it raises when a file declares
# properties after its final tool_definition (the ordering this attribution
# depends on) or when a tool name is not a readable literal. carnet#424.
sys.path.insert(0, "scripts/ci")
import tool_schema_properties as tsp

try:
    _tools, _stats = tsp.scan()
except tsp.ScanError as exc:
    print(f"SCAN_UNSOUND {exc}")
    raise SystemExit(0)

declared = {name: entry["properties"] for name, entry in _tools.items()}

UNIVERSAL = tsp.UNIVERSAL

yamls = sorted(glob.glob(os.path.join(tools_dir, "*.yaml")))
if not yamls:
    print("SCAN_EMPTY")
    raise SystemExit(0)

dead = []
for y in yamls:
    tool = os.path.basename(y)[:-5]
    if tool not in declared:
        continue  # Check 5 owns the dead-stem case
    try:
        lines = open(y, encoding="utf-8").read().splitlines()
    except OSError:
        continue
    keys, inside = [], False
    for line in lines:
        if re.match(r"^parameters:\s*$", line):
            inside = True
            continue
        if inside:
            if line and not line[0].isspace():
                break
            k = re.match(r"^  ([a-z0-9_]+):", line)
            if k:
                keys.append(k.group(1))
    for k in keys:
        if k not in declared[tool] and k not in UNIVERSAL:
            dead.append(f"{tool}.yaml: {k}")

print("\n".join(dead))
PYPARAM
)"; then
        if [[ "$PARAM_REPORT" == SCAN_UNSOUND* ]]; then
            echo -e "${RED}❌ Overlay parameter scan cannot stand behind its result:${NC}"
            echo -e "${YELLOW}   ${PARAM_REPORT#SCAN_UNSOUND }${NC}"
            FAILED=true
        elif [[ "$PARAM_REPORT" == "SCAN_EMPTY" ]]; then
            echo -e "${RED}❌ Overlay parameter scan incomplete: ${CM_ROOT}tools holds no *.yaml.${NC}"
            echo -e "${YELLOW}   The overlays moved or changed extension — point this at the new layout.${NC}"
            FAILED=true
        elif [[ -n "$PARAM_REPORT" ]]; then
            echo -e "${RED}❌ Overlay parameter(s) naming a property the Rust schema does not declare:${NC}"
            printf '%s\n' "$PARAM_REPORT" | sed 's/^/   /'
            echo -e "${YELLOW}   build_schema overlays with props.get_mut() and no else arm, so these are${NC}"
            echo -e "${YELLOW}   dropped in silence — the text is written and never served. Rename them to a${NC}"
            echo -e "${YELLOW}   declared property in dravr-contremaitre, or delete them.${NC}"
            FAILED=true
        else
            echo -e "${GREEN}✅ Overlay parameters: every tools/*.yaml parameter names a declared property.${NC}"
        fi
    else
        echo -e "${RED}❌ Overlay parameter check could not run.${NC}"
        FAILED=true
    fi
fi

# ---------------------------------------------------------------------------
# Check 8: only the bump lane moves the contremaitre pin
# ---------------------------------------------------------------------------
# The rev in Cargo.toml, its Cargo.lock entry and the five string copies under
# packages/i18n move together, and only contremaitre-bump.yml moves them, on
# main. A branch that carries them by hand conflicts with every other branch
# doing the same and with the bot, on all seven files at once — every feature
# with a new string did, from both developers (carnet#826). The order instead:
# push the strings to dravr-contremaitre, let the bump lane move the pin (it
# polls every ten minutes; `gh workflow run contremaitre-bump.yml` to go now),
# rebase, push the platform change.
#
# Judged over the commits this checkout adds to origin/main, so a branch that
# predates a bump is fine, and the bump lane — which runs this on main before
# committing — has nothing to judge. Fails closed when origin/main is absent:
# a diff that could not be computed is not a clean one.
if [[ -n "$CM_OVERRIDE" ]]; then
    echo -e "${BLUE}ℹ️  Pin ownership skipped: --contremaitre-root reads an unpinned tree.${NC}"
elif ! PIN_BASE="$(git merge-base origin/main HEAD 2>/dev/null)"; then
    echo -e "${RED}❌ Pin ownership cannot be judged: no merge base with origin/main (git fetch origin main).${NC}"
    FAILED=true
else
    PIN_MOVES=""
    pin_rev() { # $1 = commit — the contremaitre rev Cargo.toml pins there
        git show "$1:Cargo.toml" 2>/dev/null | sed -nE 's/^dravr-contremaitre = \{ git = "[^"]+", rev = "([a-f0-9]+)".*/\1/p'
    }
    lock_source() { # $1 = commit — the contremaitre source line(s) Cargo.lock records there
        git show "$1:Cargo.lock" 2>/dev/null | grep -E '^source = "git\+https://github\.com/dravr-ai/dravr-contremaitre' | sort -u
    }
    HEAD_REV="$(pin_rev HEAD)"
    HEAD_LOCK="$(lock_source HEAD)"
    # Fail closed on a read that found nothing: a rev line or lock entry whose
    # shape escaped the patterns above reads empty on both sides, and two empty
    # reads compare equal — a pass that judged nothing.
    if [[ -z "$HEAD_REV" ]]; then
        PIN_MOVES+="Cargo.toml: no dravr-contremaitre rev line at HEAD matches Check 8's pattern"$'\n'
    elif [[ "$(pin_rev "$PIN_BASE")" != "$HEAD_REV" ]]; then
        PIN_MOVES+="Cargo.toml: dravr-contremaitre rev $(pin_rev "$PIN_BASE" | cut -c1-8) → ${HEAD_REV:0:8}"$'\n'
    fi
    if [[ -z "$HEAD_LOCK" ]]; then
        PIN_MOVES+="Cargo.lock: no dravr-contremaitre source line at HEAD matches Check 8's pattern"$'\n'
    elif [[ "$(lock_source "$PIN_BASE")" != "$HEAD_LOCK" ]]; then
        PIN_MOVES+="Cargo.lock: the dravr-contremaitre source line"$'\n'
    fi
    LOCALE_MOVES="$(git diff --name-only "$PIN_BASE" HEAD -- packages/i18n/src/locales)"
    if [[ -n "$LOCALE_MOVES" ]]; then
        PIN_MOVES+="$LOCALE_MOVES"$'\n'
    fi
    if [[ -n "$PIN_MOVES" ]]; then
        echo -e "${RED}❌ This branch moves the contremaitre pin, which only the bump lane does:${NC}"
        printf '%s' "$PIN_MOVES" | sed 's/^/   /'
        echo -e "${YELLOW}   Restore those files from origin/main (git checkout origin/main -- <file>) and drop the${NC}"
        echo -e "${YELLOW}   hand bump. If the change needs newer strings: push them to dravr-contremaitre, wait for${NC}"
        echo -e "${YELLOW}   'chore(contremaitre): bump' on main (gh workflow run contremaitre-bump.yml to go now),${NC}"
        echo -e "${YELLOW}   then rebase onto origin/main.${NC}"
        FAILED=true
    else
        echo -e "${GREEN}✅ Pin ownership: no commit here moves the contremaitre pin or the string copy.${NC}"
    fi
fi

# ---------------------------------------------------------------------------
# Check 9: the use-case catalogue names only predicates and commands the
# platform knows (carnet#828)
# ---------------------------------------------------------------------------
# A use case is offered when its `requires:` predicates hold for the athlete and
# runs its `command:` when tapped. Both are platform vocabulary: a predicate the
# ranker cannot evaluate, or a command no handler answers, compiles nowhere in
# contremaitre and would only red platform main after the bump lane moved the
# pin. contremaitre's pre-push runs this script against platform origin/main, so
# the typo fails on the author's machine instead. The predicates are listed in
# scripts/ci/use-case-predicates.txt, which the platform's predicate enum is
# held to as well.
if [[ -z "$CM_ROOT" ]]; then
    echo -e "${YELLOW}⚠️  contremaitre corpus could not be resolved (offline?) — skipping the use-case check.${NC}"
else
    if USE_CASE_REPORT="$(python3 - "$CM_ROOT" "$PROJECT_ROOT" <<'PYUSECASE'
import pathlib, re, sys
cm, platform = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
catalogue = cm / "use_cases" / "catalogue.yaml"
# Spelled by code point: a quote character in this heredoc unbalances the
# command substitution around it for the shell that parses this script.
QUOTES = chr(39) + chr(34)

reads_it = any(
    "USE_CASES_YAML" in f.read_text(encoding="utf-8", errors="ignore")
    for f in (platform / "crates").rglob("*.rs")
)
if not catalogue.is_file():
    if reads_it:
        print(f"the platform reads USE_CASES_YAML but {catalogue} is missing")
        sys.exit(1)
    print("SKIP no use-case catalogue at this contremaitre rev yet")
    sys.exit(0)

vocabulary = {}
for line in (platform / "scripts/ci/use-case-predicates.txt").read_text(encoding="utf-8").splitlines():
    line = line.strip()
    if line and not line.startswith("#"):
        name, _, threshold = line.partition(">=")
        vocabulary[name] = bool(threshold)

commands = set()
for f in (platform / "commands").rglob("*.md"):
    m = re.search(r"^command:\s*(\S+)", f.read_text(encoding="utf-8"), re.M)
    if m:
        commands.add(m.group(1))

def flow_items(text):
    return [item.strip().strip(QUOTES) for item in text.strip()[1:-1].split(",") if item.strip()]

problems, entries, requires_seen = [], 0, 0
lines = catalogue.read_text(encoding="utf-8").splitlines()
i = 0
while i < len(lines):
    line = lines[i]
    if re.match(r"^\s*-\s+id:", line):
        entries += 1
    m = re.match(r"^(\s*)(?:-\s+)?requires:\s*(.*?)\s*(?:#.*)?$", line)
    if m:
        requires_seen += 1
        indent, rest = len(m.group(1)), m.group(2)
        if rest.startswith("["):
            items = flow_items(rest)
        else:
            items = []
            while i + 1 < len(lines) and re.match(r"^\s*-\s+\S", lines[i + 1]) and len(lines[i + 1]) - len(lines[i + 1].lstrip()) > indent:
                i += 1
                items.append(lines[i].strip()[1:].strip().strip(QUOTES))
        for item in items:
            for predicate in (p.strip() for p in item.split("|")):
                name, has_threshold, value = predicate.partition(">=")
                name = name.strip()
                if name not in vocabulary:
                    problems.append(f"{catalogue}:{i + 1}: unknown predicate '{name}'")
                elif vocabulary[name] != bool(has_threshold) or (has_threshold and not value.strip().isdigit()):
                    problems.append(f"{catalogue}:{i + 1}: '{predicate}' — {name} takes {'a >=N threshold' if vocabulary[name] else 'no threshold'}")
    m = re.match(r"^\s*command:\s*(\S+)", line)
    if m and m.group(1) not in ("null", "~"):
        command = m.group(1).strip(QUOTES)
        if command not in commands:
            problems.append(f"{catalogue}:{i + 1}: command '{command}' is not a platform command")
    i += 1

if entries == 0 or requires_seen == 0:
    problems.append(f"{catalogue}: no entries with 'requires:' were read — the check judged nothing")
if problems:
    print("\n".join(problems))
    sys.exit(1)
print(f"OK {entries}")
PYUSECASE
)"; then
        case "$USE_CASE_REPORT" in
            SKIP*) echo -e "${BLUE}ℹ️  Use-case catalogue: none at this contremaitre rev yet.${NC}" ;;
            OK*) echo -e "${GREEN}✅ Use-case catalogue: ${USE_CASE_REPORT#OK } entries name only known predicates and commands.${NC}" ;;
            *)
                echo -e "${RED}❌ The use-case check exited cleanly without a verdict:${NC}"
                printf '%s\n' "$USE_CASE_REPORT" | sed 's/^/   /'
                FAILED=true
                ;;
        esac
    else
        echo -e "${RED}❌ The use-case catalogue names something the platform does not know:${NC}"
        printf '%s\n' "$USE_CASE_REPORT" | sed 's/^/   /'
        echo -e "${YELLOW}   A new predicate lands in the platform first (scripts/ci/use-case-predicates.txt and the${NC}"
        echo -e "${YELLOW}   ranker), then contremaitre may name it.${NC}"
        FAILED=true
    fi
fi

if [[ "$FAILED" == "true" ]]; then
    echo -e "${RED}❌ CONTREMAITRE COUPLING CHECK FAILED${NC}"
    echo -e "${RED}Fix the drift above before pushing — these reds otherwise land on main post-merge.${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Contremaitre coupling in sync.${NC}"
exit 0
