#!/usr/bin/env bash
# ABOUTME: Copies the pinned dravr-contremaitre strings/<locale>.json over packages/i18n's catalogue,
# ABOUTME: so the platform copy of the strings moves with every contremaitre pin bump
#
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 dravr.ai
#
# dravr-contremaitre is where every user-facing string is authored. The
# platform keeps a byte-identical copy of the pinned rev's catalogue,
#
#   strings/<locale>.json  ->  packages/i18n/src/locales/<locale>/translation.json
#
# because the server compiles it in as the messaging registry's seed and both
# clients bundle it as their cold-start catalogue. The copy is regenerated by
# this script — from the contremaitre bump lane, in the same commit as the pin
# it follows — and never edited by hand: check-contremaitre-sync.sh fails any
# byte of difference.
#
# The training catalogue and the evidence corpus need no copy: the pinned
# dravr-contremaitre crate compiles them in (`dravr_contremaitre::training`,
# `dravr_contremaitre::evidence`), and the platform reads them from there.
#
# The locale set is not decided here. Both sides must name the same locales;
# a locale on one side only is refused rather than created or deleted, since
# adding a language is a platform change (SUPPORTED_LOCALES, the client config,
# the switchers), not a file copy.
#
# Idempotent: safe to run any time, and a no-op when already in sync.
#
# Usage:
#   scripts/ci/sync-contremaitre-fallback.sh            # sync in place
#   scripts/ci/sync-contremaitre-fallback.sh --check    # report drift, change nothing
#
# Exit 0 = in sync (or synced). Exit 1 = --check found drift. Exit 2 = cannot run.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

CATALOGUE_DIR="packages/i18n/src/locales"
CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

# Resolve the canonical strings out of the PINNED rev, never "whatever is
# newest". The pin is the contract every other check reads, so syncing against
# a different rev would swap one drift for another.
PINNED="$(grep -h 'dravr-contremaitre = { git' crates/*/Cargo.toml Cargo.toml \
          | grep -oE 'rev = "[a-f0-9]{7,40}"' | grep -oE '[a-f0-9]{7,40}' | sort -u)"
if [ "$(printf '%s\n' "$PINNED" | wc -l | tr -d ' ')" != "1" ] || [ -z "$PINNED" ]; then
    echo "❌ consumers disagree on the dravr-contremaitre rev, or none pins it:" >&2
    printf '   %s\n' ${PINNED:-<none>} >&2
    echo "   Bump them to one rev before syncing the strings." >&2
    exit 2
fi

# cargo's checkout directory is named by the SHORT sha.
CHECKOUT=""
for d in "${CARGO_HOME:-$HOME/.cargo}"/git/checkouts/dravr-contremaitre-*/"${PINNED:0:7}"; do
    [ -d "$d/strings" ] && CHECKOUT="$d" && break
done
if [ -z "$CHECKOUT" ]; then
    echo "❌ no checkout of dravr-contremaitre ${PINNED:0:8} with strings/ under \$CARGO_HOME/git/checkouts." >&2
    echo "   Run 'cargo fetch' (or any cargo build) first — this script reads the" >&2
    echo "   pinned tree from disk rather than cloning it a second time." >&2
    exit 2
fi
CANON="$CHECKOUT/strings"

# `|| true`: an empty directory is a finding reported below, not a crash.
upstream="$(cd "$CANON" && ls -1 ./*.json 2>/dev/null | sed -E 's|^\./||; s|\.json$||' | sort || true)"
local_set="$(cd "$CATALOGUE_DIR" && ls -1d ./*/ 2>/dev/null | sed -E 's|^\./||; s|/$||' | sort || true)"
if [ -z "$upstream" ]; then
    echo "❌ dravr-contremaitre ${PINNED:0:8} ships no strings/<locale>.json — nothing to sync from." >&2
    exit 2
fi
if [ "$upstream" != "$local_set" ]; then
    echo "❌ the locale sets differ — contremaitre ${PINNED:0:8} ships [$(echo $upstream)]," >&2
    echo "   ${CATALOGUE_DIR} holds [$(echo $local_set)]. Adding or removing a language is a" >&2
    echo "   platform change (SUPPORTED_LOCALES, the client config), never a file copy." >&2
    exit 2
fi

DRIFT=0
COUNT=0
for locale in $upstream; do
    COUNT=$((COUNT + 1))
    src="$CANON/$locale.json"
    dest="$CATALOGUE_DIR/$locale/translation.json"
    if cmp -s "$src" "$dest"; then
        continue
    fi
    if [ "$CHECK_ONLY" = "1" ]; then
        echo "❌ $dest differs from dravr-contremaitre ${PINNED:0:8} strings/$locale.json" >&2
        DRIFT=1
    else
        cp "$src" "$dest"
        echo "   copied strings/$locale.json -> $dest"
    fi
done

if [ "$DRIFT" = "1" ]; then
    echo "   Run scripts/ci/sync-contremaitre-fallback.sh; a string is changed in dravr-contremaitre, never here." >&2
    exit 1
fi
if [ "$CHECK_ONLY" = "1" ]; then
    echo "✅ ${COUNT} locale(s) byte-identical to dravr-contremaitre ${PINNED:0:8}"
else
    echo "✅ ${COUNT} locale(s) synced from dravr-contremaitre ${PINNED:0:8}"
fi
