// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Vertical text anchoring, matching SVG `dominant-baseline`.
 */
export type Baseline = "alphabetic" | "middle" | "hanging";
