// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A semantic colour, resolved by each renderer in its own theme.
 *
 * The four pillar accents are the Boreal design system's; the rest are chrome.
 * Nothing here is a hex value, which is what lets one resolved Scene render
 * correctly in both light and dark.
 */
export type ColorToken = "activity" | "nutrition" | "recovery" | "mobility" | "axis" | "grid" | "label";
