// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one column's cells should be aligned.
 */
export type ColumnAlignment = "left" | "right";
