// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorToken } from "./ColorToken";

/**
 * One legend row.
 */
export type LegendEntry = { 
/**
 * The series name.
 */
label: string, 
/**
 * The swatch colour.
 */
color: ColorToken, };
