// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteView } from "./RouteView";
import type { Scene } from "./Scene";
import type { TableView } from "./TableView";
import type { WorkoutPlanView } from "./WorkoutPlanView";

/**
 * What a renderer receives for one visual block.
 */
export type RenderBlock = { "kind": "chart" } & Scene | { "kind": "table" } & TableView | { "kind": "workout_plan" } & WorkoutPlanView | { "kind": "route" } & RouteView;
