// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The bounding box of a track, in degrees.
 *
 * Carried rather than left to each renderer so the web app, the mobile app and
 * anything else frame the same ride identically — three implementations of one
 * fold is three chances to disagree about where a route sits.
 */
export type RouteBounds = { 
/**
 * Southernmost latitude on the track.
 */
min_latitude: number, 
/**
 * Northernmost latitude on the track.
 */
max_latitude: number, 
/**
 * Westernmost longitude on the track.
 */
min_longitude: number, 
/**
 * Easternmost longitude on the track.
 */
max_longitude: number, };
