// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteBounds } from "./RouteBounds";
import type { RouteClimb } from "./RouteClimb";

/**
 * A recorded track, ready for a map renderer to draw over a basemap.
 *
 * The geometry is the athlete's own GPS trace, read out of the activity's time
 * series by the platform and handed over hydrated — this crate has no I/O, and
 * an agent could not transcribe a thousand points into a reply anyway. What is
 * resolved here are the relations every renderer would otherwise redo or get
 * wrong: the extent that frames the map before a tile loads, and the guarantee
 * that a parallel series is index-aligned with the track rather than padded to
 * fit.
 */
export type RouteView = { 
/**
 * The track as `(latitude, longitude)` degree pairs, in recorded order.
 */
coordinates: Array<[number, number]>, 
/**
 * The track's extent, for framing the map.
 */
bounds: RouteBounds, 
/**
 * Altitude in metres, one value per coordinate, or absent when the
 * activity recorded no altitude.
 */
elevation_meters: Array<number> | null, 
/**
 * Cumulative distance in metres, one value per coordinate, or absent when
 * the activity recorded no distance stream.
 */
distances_meters: Array<number> | null, 
/**
 * Climbs to pick out along the track. Empty unless the block asked for
 * them.
 */
climbs: Array<RouteClimb>, 
/**
 * The block's caption, if it carried one.
 */
title: string | null, 
/**
 * The tool the track came from.
 */
source_tool: string, };
