// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One climb along a track, addressed by index into the coordinates.
 *
 * Indices rather than a repeated sub-track: a climb is a slice of the line
 * already present, and copying its points would let the two drift.
 */
export type RouteClimb = { 
/**
 * Index into `coordinates` where the climb begins.
 */
start_index: number, 
/**
 * Index into `coordinates` where the climb ends, inclusive.
 */
end_index: number, 
/**
 * Mean gradient over the climb, in percent.
 */
avg_gradient: number, 
/**
 * The grade the climb was categorised as, as the platform's grader named
 * it.
 */
category: string, };
