// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Baseline } from "./Baseline";
import type { ColorToken } from "./ColorToken";
import type { TextAnchor } from "./TextAnchor";
import type { TextRole } from "./TextRole";

/**
 * One drawable primitive.
 */
export type SceneNode = { "node": "path", 
/**
 * SVG path data.
 */
d: string, 
/**
 * Stroke colour token.
 */
stroke: ColorToken, 
/**
 * Stroke width in scene units.
 */
width: number, } | { "node": "region", 
/**
 * SVG path data, already closed.
 */
d: string, 
/**
 * Fill colour token.
 */
fill: ColorToken, 
/**
 * Fill opacity in `0.0..=1.0`.
 */
opacity: number, } | { "node": "rect", 
/**
 * Left edge.
 */
x: number, 
/**
 * Top edge.
 */
y: number, 
/**
 * Width in scene units.
 */
width: number, 
/**
 * Height in scene units.
 */
height: number, 
/**
 * Fill colour token.
 */
fill: ColorToken, } | { "node": "line", 
/**
 * Start x.
 */
x1: number, 
/**
 * Start y.
 */
y1: number, 
/**
 * End x.
 */
x2: number, 
/**
 * End y.
 */
y2: number, 
/**
 * Stroke colour token.
 */
stroke: ColorToken, 
/**
 * Stroke width in scene units.
 */
width: number, } | { "node": "text", 
/**
 * Anchor x.
 */
x: number, 
/**
 * Anchor y.
 */
y: number, 
/**
 * The string to draw.
 */
content: string, 
/**
 * Horizontal anchoring.
 */
anchor: TextAnchor, 
/**
 * Vertical anchoring.
 */
baseline: Baseline, 
/**
 * What this text is for, which decides its size and weight.
 */
role: TextRole, 
/**
 * Colour token.
 */
color: ColorToken, };
