// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegendEntry } from "./LegendEntry";
import type { SceneNode } from "./SceneNode";
import type { ViewBox } from "./ViewBox";

/**
 * A chart resolved into positioned primitives.
 */
export type Scene = { 
/**
 * The coordinate space every node is positioned in.
 */
view_box: ViewBox, 
/**
 * Draw order. Grid and axes come first, series after, labels last.
 */
nodes: Array<SceneNode>, 
/**
 * One entry per series, for a renderer-drawn legend.
 */
legend: Array<LegendEntry>, 
/**
 * The block's caption, if it carried one.
 */
title: string | null, 
/**
 * The tool the numbers came from, for attribution in the UI.
 */
source_tool: string, };
