// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnAlignment } from "./ColumnAlignment";

/**
 * A table resolved to display strings.
 *
 * Every cell is already formatted, so a renderer never decides how a number
 * looks — which is what keeps the app and a rasterised messaging PNG showing
 * the same thing.
 */
export type TableView = { 
/**
 * Column headers.
 */
columns: Array<string>, 
/**
 * Rows, each exactly `columns.len()` long.
 */
rows: Array<Array<string>>, 
/**
 * Per-column alignment, derived from the data rather than declared.
 */
alignments: Array<ColumnAlignment>, 
/**
 * The block's caption, if it carried one.
 */
title: string | null, 
/**
 * The tool the numbers came from.
 */
source_tool: string, };
