// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a piece of text is for.
 *
 * Renderers map this to a size and weight rather than the Scene carrying one,
 * so each platform uses its own type scale and stays legible at its own
 * density.
 */
export type TextRole = "axis_tick" | "axis_title";
