// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fixed coordinate space. Renderers scale this to their container.
 */
export type ViewBox = { 
/**
 * Width in scene units.
 */
width: number, 
/**
 * Height in scene units.
 */
height: number, };
