// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A training plan, carried verbatim.
 *
 * The platform validates it against `structured-workout.schema.json` before it
 * is ever stored, so this crate neither re-validates nor reshapes it — doing
 * either would make photograveur a second authority on a format contremaitre
 * owns.
 */
export type WorkoutPlanView = { 
/**
 * The plan document, exactly as the agent emitted it.
 */
plan: unknown, 
/**
 * The tool the plan was built from.
 */
source_tool: string, };
